### ISSUE TITLE
class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found

### ISSUE THREAD

**Issue by silasfc** [paulocanedo/posmobile#19]
Running app-scripts build: --iscordovaserve --externalIpRequired --nobrowser

[18:07:12]  build dev started ... 
[18:07:12]  clean started ... 
[18:07:12]  clean finished in 2 ms 
[18:07:12]  copy started ... 
[18:07:12]  transpile started ... 
[18:07:14]  transpile finished in 1.92 s 
[18:07:14]  preprocess started ... 
[18:07:14]  deeplinks started ... 
[18:07:14]  deeplinks finished in 12 ms 
[18:07:14]  preprocess finished in 12 ms 
[18:07:14]  webpack started ... 
[18:07:14]  copy finished in 2.04 s 
[18:07:20]  webpack finished in 5.92 s 
[18:07:20]  sass started ... 
[18:07:21]  sass finished in 785 ms 
[18:07:21]  postprocess started ... 
[18:07:21]  postprocess finished in 3 ms 
[18:07:21]  lint started ... 
[18:07:21]  build dev finished in 8.68 s 
> cordova build android
⠹ Running command [18:07:22]  tslint: src/pages/map/map.ts, line: 44 
            Unused variable: 'marker' 

      L44:        let marker = map.addMarker(markeroptions).then((marker: Marker) => {
      L45:          marker.showInfoWindow();

[18:07:22]  tslint: src/pages/geolocation/geolocation.ts, line: 38 
            Unused variable: 'country' 

      L37:  this.geocoder.reverseGeocode(pos.coords.latitude, pos.coords.longitude).then((res: NativeGeocoderReverseResult) => {
      L38:    let country = this.toaster.create({
      L39:      message: res.countryName,

[18:07:22]  lint finished in 1.68 s 
✖ Running command - failed!

[ERROR] Cordova encountered an error.
        You may get more insight by running the Cordova command above directly.
        
[ERROR] An error occurred while running cordova build android (exit code 1):
        
        (truncated) ... packageDebugRenderscript UP-TO-DATE
        :CordovaLib:compileDebugRenderscript UP-TO-DATE
        :CordovaLib:generateDebugResValues UP-TO-DATE
        :CordovaLib:generateDebugResources UP-TO-DATE
        :CordovaLib:packageDebugResources UP-TO-DATE
        :CordovaLib:processDebugManifest UP-TO-DATE
        :CordovaLib:generateDebugBuildConfig UP-TO-DATE
        :CordovaLib:processDebugResources UP-TO-DATE
        :CordovaLib:generateDebugSources UP-TO-DATE
        :CordovaLib:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
        :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
        :CordovaLib:processDebugJavaRes UP-TO-DATE
        :CordovaLib:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
        :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug UP-TO-DATE
        :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
        :CordovaLib:transformNative_libsWithMergeJniLibsForDebug UP-TO-DATE
        :CordovaLib:transformNative_libsWithSyncJniLibsForDebug UP-TO-DATE
        :CordovaLib:bundleDebug UP-TO-DATE
        :CordovaLib:preReleaseBuild UP-TO-DATE
        :CordovaLib:checkReleaseManifest
        :CordovaLib:prepareReleaseDependencies
        :CordovaLib:compileReleaseAidl UP-TO-DATE
        :CordovaLib:compileReleaseNdk UP-TO-DATE
        :CordovaLib:copyReleaseLint UP-TO-DATE
        :CordovaLib:mergeReleaseShaders UP-TO-DATE
        :CordovaLib:compileReleaseShaders UP-TO-DATE
        :CordovaLib:generateReleaseAssets UP-TO-DATE
        :CordovaLib:mergeReleaseAssets UP-TO-DATE
        :CordovaLib:mergeReleaseProguardFiles UP-TO-DATE
        :CordovaLib:packageReleaseRenderscript UP-TO-DATE
        :CordovaLib:compileReleaseRenderscript UP-TO-DATE
        :CordovaLib:generateReleaseResValues UP-TO-DATE
        :CordovaLib:generateReleaseResources UP-TO-DATE
        :CordovaLib:packageReleaseResources UP-TO-DATE
        :CordovaLib:processReleaseManifest UP-TO-DATE
        :CordovaLib:generateReleaseBuildConfig UP-TO-DATE
        :CordovaLib:processReleaseResources UP-TO-DATE
        :CordovaLib:generateReleaseSources UP-TO-DATE
        :CordovaLib:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
        :CordovaLib:compileReleaseJavaWithJavac UP-TO-DATE
        :CordovaLib:processReleaseJavaRes UP-TO-DATE
        :CordovaLib:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
        :CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
        :CordovaLib:mergeReleaseJniLibFolders UP-TO-DATE
        :CordovaLib:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
        :CordovaLib:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
        :CordovaLib:bundleRelease UP-TO-DATE
        :prepareComAndroidSupportSupportV42400Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesBase1024Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesBasement1024Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesLocation1024Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesMaps980Library UP-TO-DATE
        :prepareComGoogleAndroidGmsPlayServicesTasks1024Library UP-TO-DATE
        :prepareOrgApacheCordovaCordovaLib623DebugLibrary UP-TO-DATE
        :prepareDebugDependencies
        :compileDebugAidl UP-TO-DATE
        :compileDebugRenderscript UP-TO-DATE
        :generateDebugBuildConfig UP-TO-DATE
        :generateDebugResValues UP-TO-DATE
        :generateDebugResources UP-TO-DATE
        :mergeDebugResources UP-TO-DATE
        :processDebugManifest UP-TO-DATE
        :processDebugResources UP-TO-DATE
        :generateDebugSources UP-TO-DATE
        :incrementalDebugJavaCompilationSafeguard UP-TO-DATE
        :compileDebugJavaWithJavac
        :compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
        /dados/FACTO/PLHB/HoraDoPao/platforms/android/src/plugin/google/maps/PluginGroundOverlay.java:43: error: cannot access AbstractSafeParcelable
              options.anchor((float)anchor.getDouble(0), (float)anchor.getDouble(1));
                     ^
          class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        1 error
        :compileDebugJavaWithJavac FAILED
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        
        BUILD FAILED
        
        Total time: 1.632 secs
        Error: /dados/FACTO/PLHB/HoraDoPao/platforms/android/gradlew: Command failed with exit code 1 Error output:
        /dados/FACTO/PLHB/HoraDoPao/platforms/android/src/plugin/google/maps/PluginGroundOverlay.java:43: error: cannot access AbstractSafeParcelable
              options.anchor((float)anchor.getDouble(0), (float)anchor.getDouble(1));
                     ^
          class file for com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable not found
        Note: Some input files use or override a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        1 error
        
        FAILURE: Build failed with an exception.
        
        * What went wrong:
        Execution failed for task ':compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.
        
        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by paulocanedo** [comment]
veja se esse link te ajuda:
http://stackoverflow.com/questions/41030573/ionic-v2-google-maps-api-android-build-error-cannot-access-abstractsafeparcelab

**Comment by silasfc** [comment]
Sim, tinha resolvido ontem fazendo isso mesmo. Resolvido! De todo modo, obrigado pela dica!
